### ISSUE TITLE
Tables: Padding of cell content

### ISSUE THREAD

**Issue by digital-ember** [mbeddr/mbeddr.core#1782] opened 2017-10-16 10:00 UTC
I experience problems trying to add padding to content of cells. Assume I have a node of INamedConcept as a cell content, and I want to add `padding-top: 5 spaces` to its Editor_Cell projection.

The result looks like this:
![image](https://user-images.githubusercontent.com/19651078/31606142-98a84be2-b268-11e7-9e63-3a1aa85248ab.png)
The padding is applied to the bottom.

The other padding options seem to be fine, applying a padding styling like this, for example:
```
<no base style> {  
  padding-top : 5 spaces   
  padding-left : 3 spaces  
  padding-right : 7 spaces 
  padding-bottom : 8 spaces
}
```
leads to this projection (annotated):
![image](https://user-images.githubusercontent.com/19651078/31606413-57f957e8-b269-11e7-9003-b5b0040e4930.png)

Changing the `vertical-alignment` property of either the cell or the content did not seem to have any effect.

**Comment by slisson** [comment] 2017-11-08 12:43
As an alternative import the language de.itemis.mps.editor.celllayout and use the margin styles.

**Comment by alexanderpann** [comment] 2023-02-19 08:03
I am closing this issue because this behavior is not reproducible for me anymore. Please open an issue in [MPS-Extensions](https://github.com/JetBrains/MPS-extensions/issues) in case you are still affected by this and have a minimal reproducible example. Two working examples with:
```
padding-top : 5 spaces   
padding-left : 3 spaces  
padding-right : 7 spaces 
padding-bottom : 1 spaces
```

<img width="317" alt="Screenshot 2023-02-19 at 09 00 27" src="https://user-images.githubusercontent.com/88385944/219936334-b74f1f50-600e-409a-836a-1894d8546da9.png">

<img width="317" alt="Screenshot 2023-02-19 at 09 01 33" src="https://user-images.githubusercontent.com/88385944/219936343-3e9e613f-2f7b-46fe-a3be-23e393d0c786.png">

**Closed by alexanderpann** 2023-02-19 08:03 UTC
Labels: prio.low
