### ISSUE TITLE
Optional leads to compile error

### ISSUE THREAD

**Issue by markusvoelter** [mbeddr/mbeddr.core#1261] opened 2016-01-04 11:43 UTC
Replace the conditional for the constraint with an optional cell to see the exception:

project: org.iets3.core (/Users/markusvoelter/Documents/mbeddr/iets3.core/code/languages/org.iets3.core)
module:  org.iets3.components.functional
model:   org.iets3.components.functional.editor
node:    DataItemPortType_Editor [ConceptEditorDeclaration](root)
url:     http://localhost:8080/select/org.iets3.core/r:b08adb63-6835-487f-a8d6-f6cefb8f131b/7804632404593474276/

![screen shot 2016-01-04 at 12 42 46](https://cloud.githubusercontent.com/assets/592330/12089020/add6bdfc-b2e0-11e5-8355-db994607d2c7.png)

**Comment by slisson** [comment] 2016-01-05 10:13
The problem is, that some editor components are inlined (cells from the editor component are copied into the generated model) and then the model contains concepts from languages that are not part of the generation plan.

A workaround is to add the languages ("querylist" and "tooltip" in your case) to "Languages engaged on generation".

**Comment by slisson** [comment] 2016-01-07 12:22
TODO: Show a warning or error

**Comment by alexanderpann** [comment] 2023-02-16 11:38
I am closing because this exact use case is working now.

**Closed by alexanderpann** 2023-02-16 11:38 UTC
Labels: comp.grammarcells
