### ISSUE TITLE
Copying slisson table results in NPE

### ISSUE THREAD

**Issue by digital-ember** [mbeddr/mbeddr.core#1972] opened 2018-07-30 07:42 UTC
Hi,
this bug occurs with mbeddr platform build version 1.0.20402.
pressing Ctrl+C when selecting a concept that projects a table we get the following NPE:

java.lang.NullPointerException
        at de.itemis.mps.editor.celllayout.layout.AbstractGridLayout.toText(AbstractGridLayout.java:392)
        at de.itemis.mps.editor.celllayout.runtime.LayoutableCollectionAdapter.toText(LayoutableCollectionAdapter.java:491)
        at de.itemis.mps.editor.celllayout.runtime.TopDownCellLayoutAdapter.doLayoutText(TopDownCellLayoutAdapter.java:50)
        at de.itemis.mps.editor.celllayout.runtime.LayoutInterceptor.doLayoutText(LayoutInterceptor.java:80)
        at de.itemis.mps.editor.celllayout.runtime.PunctuableLayout.doLayoutText(PunctuableLayout.java:39)
        at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.renderText(EditorCell_Collection.java:783)
        at jetbrains.mps.nodeEditor.text.TextRenderUtil.renderText(TextRenderUtil.java:43)
        at jetbrains.mps.nodeEditor.text.TextRenderUtil.getTextBuilderForSelectedCellsOfEditor(TextRenderUtil.java:51)
        at jetbrains.mps.nodeEditor.cellActions.CellAction_CopyNode.extractSelection(CellAction_CopyNode.java:74)
        at jetbrains.mps.nodeEditor.cellActions.CellAction_CopyNode.execute(CellAction_CopyNode.java:59)
        at jetbrains.mps.nodeEditor.actions.CellActionExecuter$1.doExecute(CellActionExecuter.java:57)
        at jetbrains.mps.editor.runtime.commands.EditorCommand.run(EditorCommand.java:56)
        at jetbrains.mps.smodel.WorkbenchModelAccess$CommandRunnable.lambda$run$0(WorkbenchModelAccess.java:449)
        at jetbrains.mps.smodel.WorkbenchModelAccess.runWriteAction(WorkbenchModelAccess.java:97)
        at jetbrains.mps.smodel.WorkbenchModelAccess$CommandRunnable.run(WorkbenchModelAccess.java:446)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:95)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
        at jetbrains.mps.smodel.WorkbenchModelAccess.runWriteActionInCommand(WorkbenchModelAccess.java:311)
        at jetbrains.mps.smodel.WorkbenchModelAccess.executeCommand(WorkbenchModelAccess.java:307)
        at jetbrains.mps.project.ProjectModelAccess.executeCommand(ProjectModelAccess.java:43)
        at jetbrains.mps.nodeEditor.actions.CellActionExecuter.lambda$execute$1(CellActionExecuter.java:54)
        at jetbrains.mps.nodeEditor.EditorContext.lambda$runWithContextCell$3(EditorContext.java:291)
        at jetbrains.mps.nodeEditor.EditorContext.runWithContextCell(EditorContext.java:302)
        at jetbrains.mps.nodeEditor.EditorContext.runWithContextCell(EditorContext.java:290)
        at jetbrains.mps.nodeEditor.actions.CellActionExecuter.execute(CellActionExecuter.java:52)

This used to work in mbeddr platform build 1.0.19882.
This can be reproduced with the sandbox tables in the mps-sl-all project.

**Comment by alexanderpann** [comment] 2023-02-19 08:12
I am closing because this is not reproducible anymore. I guess this was fixed in https://github.com/JetBrains/MPS-extensions/commit/d6822ec6d4022a14aeaeaead57fe44875bb3912c.

**Closed by alexanderpann** 2023-02-19 08:12 UTC
