### ISSUE TITLE
Clang / LLDB Support

### ISSUE THREAD

**Issue by sirinath** [mbeddr/mbeddr.core#1219] opened 2015-08-12 04:33 UTC
Is it possible to support the Clang LLDB stack? Going forward LLVM will have better support in all platforms than GCC toolchain as companies like MS are also working on LLVM/Clang based tools:
https://github.com/dotnet/llilc
https://github.com/Microsoft/llvm
https://github.com/Microsoft/WinObjC
https://github.com/Microsoft/MIEngine
https://github.com/Microsoft/clang-tools-extra
https://github.com/Microsoft/clang

**Comment by bkolb** [comment] 2015-08-13 10:09
Yes, we would very much like to see that. Currently however, there is no support for LLDB in Eclipse and we reuse that part to integrate with GDB. As soon as support for LLDB is provided there we will also integrate it. As always: Contributions are very welcome!

**Comment by coolya** [comment] 2016-11-14 12:08
duplicate of #1147

**Closed by coolya** 2016-11-14 12:08 UTC
