### ISSUE TITLE
Copy and Paste in Tables doesnt work as expected

### ISSUE THREAD

**Issue by sele95** [mbeddr/mbeddr.core#1778] opened 2017-10-06 07:34 UTC
I'd like to report a potential bug in the *slisson.tables* implementation.

I've defined a table with 4 columns. Now, I want to copy a complete row (like in MS Word) and paste it afterwards.

The entries are inserted 4 times. If I select 3 column from a row, it gets inserted 3 times and so on.

Do you have any idea why this is happening? 

 

Thanks, and best regards

**Comment by alexanderpann** [comment] 2023-02-19 07:51
I am closing this issue because this behavior is not reproducible for me and there are no current known paste issues with tables anymore. Please open an issue in [MPS-Extensions](https://github.com/JetBrains/MPS-extensions/issues) in case you are still affected by this and have a minimal reproducible example.

**Closed by alexanderpann** 2023-02-19 07:51 UTC
