### ISSUE TITLE
Actions for CellModel_Collapsible

### ISSUE THREAD

**Issue by josefmueller** [mbeddr/mbeddr.core#1654] opened 2017-03-13 13:57 UTC
It would be really handy if MPS folding actions (bellow) could be used also for CellModel_Collapsible. Would it be possible?

![image](https://cloud.githubusercontent.com/assets/15520928/23856918/8b21e4a0-07fb-11e7-89da-8e18edc4761e.png)

Are there any actions like these for CellModel_Collapsible?

**Comment by alexanderpann** [comment] 2023-02-16 12:31
Duplicate of https://github.com/JetBrains/MPS-extensions/issues/573.

**Closed by alexanderpann** 2023-02-16 12:31 UTC
Labels: prio.low
